[package]
name = "kafka-auth-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO select features
tokio = { version = "1.37.0", features = ["full"] }
byteorder = "1.5.0"

[dev-dependencies]
rstest = "0.19.0"
